---
# INTERACTSH-WEB VARS
web_port: 443
interactsh_web_domain: example.com
volume_directory: "{{ tool_directory }}"
fullchain_path: "{{ tool_directory }}/fullchain.pem"
privkey_path: "{{ tool_directory }}/privkey.pem"