---
# Playbook to install external pentest environment
- hosts: attack
  become: true
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  roles:
    - role: common
    - role: gotools

# Playbook to deploy interactsh server
- hosts: interactsh
  become: true
  roles:
    - role: interactsh-server