---
# INTERACTSH-SERVER HANDLERS

- name: shutdown nginx
  service: 
    name: nginx
    state: stopped
    enabled: no

- name: shutdown docker
  service:
    name: docker
    state: stopped
    enabled: no