---
# INTERACTSH-WEB HANDLERS

- name: shutdown nginx
  service: 
    name: nginx
    state: stopped
    enabled: no

- name: restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: shutdown docker
  service:
    name: docker
    state: stopped
    enabled: no